[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = [
    'aave-helpers/=lib/aave-helpers/src/',
    'solidity-utils/=lib/aave-helpers/lib/solidity-utils/src/'
]
fs_permissions = [
    { access = "write", path = "./reports" }
]
optimizer = true
ffi = true

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
